import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'swiper/css';
import 'swiper/css/navigation';
import './globals.css';
import Topbar from '@/Components/Modules/Topbar/Topbar';
import StoreProvider from '@/Components/Modules/StoreProvider/StoreProvider';
import Footer from '@/Components/Modules/Footer/Footer';
import FetchProvider from '@/Components/Modules/FetchProvider/FetchProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const inter = Inter({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body cz-shortcut-listen="true" className={inter.className}>
                <StoreProvider>
                    <FetchProvider>
                        <Topbar />
                        {children}
                        <Footer />
                    </FetchProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
