import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Topbar from '@/Components/Modules/Topbar/Topbar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const inter = Inter({
    subsets: ['latin'],
    weight: '400',
});
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body cz-shortcut-listen="true" className={inter.className}>
                <Topbar />
                {children}
            </body>
        </html>
    );
}
